### ISSUE TITLE
Migrate to FastAPI

### ISSUE THREAD

**Issue by rclement** [rclement/mailer#2]
Currently, `mailer` is leveraging the following libraires to provide all of its features:

- `flask`: API endpoints
- `flask-apispec`: JSON schema serialization/deserialization + API documentation generation
- `flask-cors`: CORS origins protection
- `flask-limiter`: API rate-limiting
- `flask-recaptcha`: API recaptcha protection on POST endpoints
- `flask-talisman`: generic security API headers generation

No asynchronous / background task mechanism can be used, besides leveraging a task broker such as `celery` with a Redis/AMQP backend, which might be an issue when switching to generic SMTP e-mail sending (cf. #1)

Migrating to `fastapi` will provide the same feature set and more thanks to its ASGI nature:

- `fastapi` (+ `starlette` + `pydantic`): API endpoints, CORS middleware, in-process background tasks, endpoints schema serialization/deserialization, settings validation, API documentation generation, etc.
- ReCaptcha validation: only a simple middleware is required (cf. [`flask-recaptcha`](https://github.com/mardix/flask-recaptcha/blob/master/flask_recaptcha.py))
- Rate-limiting: nothing built-in. As the current implementation does not seem to be used in production-ready serverless context (using an external KV-store such as Redis instead of in-memory store), this is not really an issue. However, developing a small middleware using [`limits`](https://limits.readthedocs.io/en/stable/) could be done (same as `flask-limiter`).

Cherry on the cake: switching to `fastapi` will allow to fully make use of Python type hinting system using `mypy`!

**Comment by rclement** [comment]
Rate-limiting is no longer implemented with the FastAPI refactor.

**Comment by jeanlst** [comment]
Hey @rclement , what did you end up using to replace flask-talisman?

**Comment by rclement** [comment]
@jeanlst basically nothing for this project. You have to understand security API headers are only there to inform browsers about best practices but do not enforce anything, and are easily bypassed by using a low-level client (`curl`, `httpie`, `requests`, etc.).

You want security for your API? You do have to enforce things server-side when handling HTTP requests (origin, API tokens, etc.)

**Comment by rglynn** [comment]
@rclement -- what was the middleware for implementing recaptcha? I can't find anything via Google to when switching to fast from flask regarding recaptcha.

**Comment by rclement** [comment]
@rglynn I simply reimplemented the the verification request: https://github.com/rclement/mailer/blob/master/mailer/recaptcha.py
